server:
  port: 9090
  
#undertow:
#   buffer-size: 1073741824
#   direct-buffers: 1073741824
#   io-threads: 100000
#   worker-threads: 100000
#   max-http-post-size: 1073741824    

management:
  security:  
    enabled: true 
    
spring:
  application:
    name: skipthedishes-sp-fair
#    profiles:
#    active: default
  session:
    store-type: jdbc   
  jpa:
      database: MYSQL
      hibernate:
        ddl-auto: none
#        dialect:  org.hibernate.dialect.MySQLDialect        
  datasource:
        url: jdbc:mysql://127.0.0.1:3306/skipthedishes-sp-fair?zeroDateTimeBehavior=convertToNull&amp;useUnicode=yes&amp;characterEncoding=UTF-8
        username: skipthedishes
        password: skipthedishes
        driver-class-name: com.mysql.jdbc.Driver              
