server:
  port: 8080

spring:
  application:
    name: skipthedishes-sp-fair
#    profiles:
#    active: default
  session:
    store-type: jdbc

  jpa:
      database: MYSQL
      hibernate:
        ddl-auto: none
#        dialect:  org.hibernate.dialect.MySQLDialect
  datasource:
        url: jdbc:mysql://127.0.0.1:3306/skipthedishes-sp-fair?zeroDateTimeBehavior=convertToNull&amp;useUnicode=yes&amp;characterEncoding=UTF-8
        username: skipthedishes-sp-fair
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver              

# Default security
security:
    user:
      name: user
      password: password
      role: ADMIN

# Logger
logging:
  level:
    org.springframework.web: INFO
    org.hibernate: WARN
    br.sp.fair: INFO
  file: ./skipthedishes-sp-fair.log
      